name: fish_redux_ns
description: Fish Redux is an assembled flutter application framework based on Redux state management.
version: 0.3.7-ns
#homepage: https://github.com/alibaba/fish-redux

environment:
    sdk: ">=3.0.0 <4.0.0"
dependencies:
    flutter:
        sdk: flutter
    collection: ^1.15.0-nullsafety.4

dev_dependencies:
    test: any
    flutter_test:
        sdk: flutter

flutter: